line-length = 100
indent-width = 4
cache-dir = ".ruff_cache"
extend-exclude = ["*.pyi"]

[format]
docstring-code-format = true
docstring-code-line-length = 100
indent-style = "space"
line-ending = "lf"
quote-style = "double"
